Seminar 06: Fitting and interpreting linear models (high volume)
================================================================

Runthrough of STAT540 [seminar06](http://www.ugrad.stat.ubc.ca/~stat540/seminars/seminar06_highVolumeLinearModelling.html)

Preliminaries
-------------

> If you haven't done so already, install limma 

```{r eval=FALSE}
source("http://www.bioconductor.org/biocLite.R")
biocLite("limma")
biocLite("statmod")
```

> Load the limma and/or lattice package, if you need to:

```{r}
library(limma)
library(lattice)
library(ggplot2)
```

> Load the photoRec dataset:

```{r}
prDat <- read.table("../../../stat540/stat540_2014/examples/photoRec/data/GSE4051_data.tsv")
str(prDat, max.level = 0)
prDes <- readRDS("../../../stat540/stat540_2014/examples/photoRec/data/GSE4051_design.rds")
str(prDes)
```

> You might want to use the functions you wrote last week to extract and stripplot excerpts from the photoRec dataset. If you stored the code defining those functions cleanly in a script, you could make them available now by using the source() function.

I've got everything in an .Rmd document, so I'll add those functions back here:

```{r}
prepareData <- function(keepGenes){
  miniDat <- subset(prDat, rownames(prDat) %in% keepGenes)
  miniDat <- data.frame(gExp = as.vector(t(as.matrix(miniDat))),
                        gene = factor(rep(rownames(miniDat), 
                                      each = ncol(miniDat)),
                                       levels = keepGenes))
  miniDat <- suppressWarnings(data.frame(prDes, miniDat))
}
makeStripplot <- function(x, ...){
  stripplot(gExp ~ devStage | gene, x,
          group = gType, jitter.data = TRUE,
          auto.key = TRUE, type = c('p', 'a'), grid = TRUE, 
          ...)
}
makeggStripplot <- function(x){
  p <- ggplot(x, aes(factor(devStage), gExp, colour=gType, group=gType))
  p <- p + geom_point(size=5) + facet_grid(. ~ gene)
  p <- p + stat_summary(fun.y = mean, geom="line")
  p <- p + scale_colour_brewer(palette='Set1')
  p
}
```

The difficulty in estimating gene-wise variance
-----------------------------------------------


